config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users

  # UX redirections
  get '/dashboard', to: redirect("/dashboard/bookings")
  get '/dashboard/bars/:id', to: redirect("/dashboard/bars")

  get '/dashboard/bookings', to: 'bookings#index', as: "dashboard_bookings"
  get '/dashboard/bars', to: 'bars#owner_index', as: "dashboard_bars"
  get '/dashboard/bars/:bar_id/bookings', to: 'bookings#owner_index', as: "dashboard_owner_bookings"

  resources :bars, except: :destroy do
    resources :bookings, only: %i[create]
  end

  resources :bookings, except: %i[index create] do
    resources :reviews, only: %i[create]
  end

  post '/bookings/:id/cancellation', to: 'bookings#cancel', as: "booking_cancellation"
end

app/models/bar.rb
# frozen_string_literal: true

##
# Bar model
# Definition and instance methods
class Bar < ApplicationRecord
  include PgSearch::Model
  has_many :bookings, dependent: :nullify
  has_many :reviews, through: :bookings
  belongs_to :owner, inverse_of: :bars, class_name: "User", foreign_key: "user_id"
  has_many_attached :photos
  geocoded_by :address

  pg_search_scope :bar_search,
                  against: %i[name address],
                  using: {
                    tsearch: { prefix: true }
                  }

  after_validation :geocode, if: :will_save_change_to_address?
  validates :name, :address, presence: true # , uniqueness: true
  validates :price, :description, :capacity, :opening_start, :opening_end, :photos, presence: true

  attr_accessor :distance

  def average_rating
    reviews.empty? ? nil : reviews.map(&:rating).sum.fdiv(reviews.size).round(2)
  end
end

##
# Bar model
# Class methods
class Bar
  # Sorting Method
  # But the bars with active bookings first, then the others, ordered alphabetically
  # Bars with active bookings are ordered by the earliest booking
  def self.sort_by_bookings(bar_list = Bar.all)
    return [] if bar_list.blank?

    bars_with_active_bookings = bar_list.select { |bar| bar.bookings.where(state: "À venir").any? }
                                        .sort_by do |bar|
      bar.bookings.where(state: "À venir")
         .order(:starts_at)
         .limit(1).first.starts_at.to_i
    end

    bars_without_active_bookings = bar_list.reject { |bar| bar.bookings.where(state: "À venir").any? }
                                           .sort_by(&:name)

    [bars_with_active_bookings, bars_without_active_bookings].flatten
  end
end

app/controllers/bars_controller.rb
# frozen_string_literal: true

class BarsController < ApplicationController
  before_action :set_bar, only: %w[show edit update]
  skip_before_action :authenticate_user!, only: %w[index show]

  def index
    @query = params[:query]
    @bars = @query.present? ? set_policy_scope : policy_scope(Bar)
    compute_distance

    @markers = create_markers(@bars)
  end

  def owner_index
    @bars = Bar.sort_by_bookings(current_user.bars)

    @bars.each { |bar| authorize bar }
    authorize @bars if @bars.empty?
  end

  def show
    @booking = Booking.new
  end

  def new
    @bar = Bar.new
    authorize @bar
  end

  def create
    @bar = Bar.new(bar_params)
    @bar.owner = current_user
    authorize @bar
    if @bar.save
      redirect_to bar_path(@bar)
    else
      render :new
    end
  end

  def edit; end

  def update
    @bar.update(bar_params)
    authorize @bar
    @bar.save
    redirect_to bar_path(@bar)
  end

  private

  def compute_distance
    position = @query.present? ? Geocoder.search(@query).first : Geocoder.search("16 villa Gaudelet").first
    @bars.each do |bar|
      bar.distance = (1_000 * Geocoder::Calculations.distance_between(
        position.coordinates,
        [bar.latitude, bar.longitude]
      )).round
    end
  end

  def create_markers(bars)
    bars.map do |bar|
      {
        lat: bar.latitude,
        lng: bar.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { bar: bar }),
        image_url: helpers.asset_url('barbie.png')
      }
    end
  end

  def set_bar
    @bar = Bar.find(params[:id])
    authorize @bar
  end

  def bar_params
    params.require(:bar).permit(
      :name,
      :address,
      :capacity,
      :opening_start,
      :opening_end,
      :description,
      :price,
      photos: []
    )
  end

  def set_policy_scope(distance = 1)
    bar_distance = Bar.near(@query, distance)
    if bar_distance.present?
      policy_scope(bar_distance)
    else
      new_dist = distance < 5 ? 1 : 100
      set_policy_scope(distance + new_dist)
    end
  end
end

app/views/bars/_average_rating.html.erb
<div class="average-rating">
  <%
      if bar.average_rating
        average_stars = (bar.average_rating * 2).round / 2.0
        number_full_stars = average_stars.floor
        half_star = average_stars % 1 == 0 ? 0 : 1
        number_empty_stars = 5 - (number_full_stars + half_star)
      end
  %>

  <% if bar.average_rating %>
    <% number_full_stars.times do %>
      <%= icon("fas", "star") %>
    <% end %>

    <%= icon("fas", "star-half-alt") if half_star == 1 %>

    <% number_empty_stars.times do %>
      <%= icon("far", "star") %>  
    <% end %>
  <% end %>
</div>

app/views/bars/_booking_form.html.erb
<div data-controller="pick-date">
  <div data-controller="guest-count"
      data-guest-count-max-guest="<%= @bar.capacity %>"
      >
      <%= simple_form_for [@bar, @booking] do |f| %>
        <%= f.input :starts_at, as: :hidden,
                    readonly: true,
                    input_html: {
                      value: Time.parse('20:00 +0100') + 1.day,
                      data: { target: "pick-date.startsAt" }
                    }
        %>
        <%= f.input :ends_at, as: :hidden,
                    readonly: true,
                    input_html: {
                      value: Time.parse('21:00 +0100') + 1.day,
                      data: { target: "pick-date.endsAt" }                    }
        %>
        <%= f.input :guest_number, as: :hidden,
                    readonly: true,
                    input_html: {
                      value: 2,
                      data: { target: "guest-count.countField" }
                    }
        %>
      <% end %>

      <div id="guest-count">
        <div>Participants :</div>
        <div class="count-button"
              data-action="click->guest-count#remove"
              data-target="guest-count.minus"
              >
              <%= icon("fas", "minus") %>
        </div>
        <input type="text"
                data-target="guest-count.number"
                data-action="keyup->guest-count#validateField"
                value="2"
                >
                <div class="count-button"
                    data-action="click->guest-count#add"
                    data-target="guest-count.plus"
                    >
                    <%= icon("fas", "plus") %>
                </div>
      </div>
  </div>

  <div class="time-date-pickers">
    <input data-controller="flatpickr"
            data-target="pick-date.date"
            data-action="change->pick-date#setTimeRange"
            data-flatpickr-min-date="<%= Time.zone.now %>"
            data-flatpickr-max-date="<%= Time.zone.now + 30.days %>"
            value="<%= Time.zone.now + 1.days %>"
            type="hidden"
            >
    <div id="timers">
      <div class="de-a">De</div>
      <input data-controller="flatpickr"
            data-target="pick-date.from"
            data-action="change->pick-date#setTimeRange"
            data-flatpickr-enable-time="true"
            data-flatpickr-no-calendar="true"
            value="20:00"
            id="time-from"
            >
      <div class="de-a">À</div>
      <input data-controller="flatpickr"
            data-target="pick-date.to"
            data-action="change->pick-date#setTimeRange"
            data-flatpickr-enable-time="true"
            data-flatpickr-no-calendar="true"
            value="21:00"
            id="time-to"
            >
    </div>
  </div>
</div>

app/views/bars/_info_window.html.erb
<div class="img-map" style="background-image: url(<%= cl_image_path(bar.photos.sample.key) %>)"></div>
<h2><%= bar.name %></h2>
<p class="m-0 text-muted"><%= bar.address %></p>
<%= render 'components/button_link', text: "Voir le bar", link: bar_path(bar) %>

app/views/bars/_review_form.html.erb
<div class="add-review" data-controller="star-rating">
  <h3>Your review...</h3>
  <div class="stars" data-action="mouseleave->star-rating#showRating">

<%
    stimulus_hooks = {
      "data-target" => "star-rating.star",
      "data-action" => "click->star-rating#setRating \
                        mouseover->star-rating#chooseRating"
    }
%>

    <% 5.times do |i| %>
      <% stimulus_hooks["data-id"] = i + 1 %>
      <div class="star"><%= icon("far", "star", stimulus_hooks) %></div>
    <% end %>
  </div>

  <%= simple_form_for [@bar, @review] do |f| %>
    <%= f.input :content, label: false %>
    <%= f.input :rating, as: :hidden, input_html: { data: { target: "star-rating.form" } } %>
    <%= f.submit "Add review" %>
  <% end %>
</div>

app/views/bars/_reviews.html.erb
<% unless @bar.reviews.empty? %>
  <div class="reviews">
    <ul>
      <% @bar.reviews.each do |review|%>
        <li>
          <div class="rating-stars mt-2">
            <% review.rating.times do %>
              <div><%= icon("fas", "star") %></div>
            <% end %>
            <% (5 - review.rating).times do %>
              <div><%= icon("far", "star") %></div>
            <% end %>
          </div>
          <div>
            <%= review.content %>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/bars/edit.html.erb
<div class="form-component-bar">
  <div class="main-container-form-bar">
    <div class="row">
      <div class="col-3">
        <img src="https://cdn.dribbble.com/users/19319/screenshots/6961556/neonsign_concepts_2x.png" alt="">
      </div>
      <div class="col-4 offset-2 form-new my-4 p-4 shadow ">
        <div class="title-form text-center my-3">
          <h3><strong>Editez votre établissement</strong></h3>
        </div>
        <%= simple_form_for @bar do |f| %>
          <%= f.input :name, label: "Nom du bar", placeholder: 'Union Pool', required: false %>
          <%= f.input :description, placeholder: 'Brooklyn nightlife', required: false %>
          <%= f.input :address, label: "Adresse", placeholder: '484 Union Ave, Brooklyn, NY 11211, États-Unis', required: false %>
          <div class="d-flex justify-content-between">
            <div style='width: 185px;'><%= f.input :opening_start, as: :time, label: "Ouverture", html5: true, required: false%></div>
            <div style='width: 185px;'><%= f.input :opening_end, as: :time, label: "Fermeture", html5: true, required: false%></div>
          </div>
          <div class="d-flex justify-content-between">
            <div style='width: 180px;'><%= f.input :capacity, placeholder: '250', label: "Capacité", required: false %></div>
            <div style='width: 180px;'><%= f.input :price, placeholder: '600 $', label: "Prix", required: false %></div>
          </div>
          <%= f.input :photos, as: :file, input_html: { multiple: true } %>
          <%= f.button :submit, class: "btn-primary my-3" %>
          <p class="pl-2"><%= link_to "Back", :back %></p>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/bars/index.html.erb
<div class="bars-index">
  <div class="cards-bar row d-flex">
    <div class="col-7 d-flex justify-content-center flex-wrap">
      <% @bars.each do |bar| %>
        <div class="card-bar-info col-5 m-4">
          <%= render "components/bar_card", bar: bar %>
        </div>
      <% end %>
    </div>
    <div id="map" class="col-5 sticky-top sticky-offset p-0"
     style="width: 100%;
     height: 700px;"
     data-markers="<%= @markers.to_json %>"
     data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
     </div>
  </div>
</div>

app/views/bars/new.html.erb
<div class="form-component-bar">
    <div class="background-form d-flex justify-content-center">
      <div class="form-new my-4 p-4 shadow ">
        <div class="title-form text-center my-3">
          <h3><strong>Ajoutez votre établissement</strong></h3>
        </div>
        <%= simple_form_for @bar do |f| %>
          <%= f.input :name, label: "Nom du bar", placeholder: 'Union Pool', required: false %>
          <%= f.input :description, placeholder: 'Brooklyn nightlife', required: false %>
          <%= f.input :address, label: "Adresse", placeholder: '484 Union Ave, Brooklyn, NY 11211, États-Unis', required: false %>
          <div class="d-flex justify-content-between">
            <div style='width: 185px;'><%= f.input :opening_start, as: :time, label: "Ouverture", html5: true, required: false%></div>
            <div style='width: 185px;'><%= f.input :opening_end, as: :time, label: "Fermeture", html5: true, required: false%></div>
          </div>
          <div class="d-flex justify-content-between">
            <div style='width: 180px;'><%= f.input :capacity, placeholder: '250', label: "Capacité", required: false %></div>
            <div style='width: 180px;'><%= f.input :price, placeholder: '600 $', label: "Prix", required: false %></div>
          </div>
          <%= f.input :photos, as: :file, input_html: { multiple: true }, required: false , class: "btn-primary my-3" %>
          <%= f.button :submit, class: "btn-primary my-3" %>
        <% end %>
      </div>
    </div>
</div>

app/views/bars/owner_index.html.erb
<div class="dashboard">
  <%= render "components/dashboard_menu" %>
    <% if @bars.first.is_a? Bar %>
      <div class="dashboard-content">
        <div class="bookings-content bars">
          <h1>Mes établissements</h1>

          <% @bars.each do |bar| %>
            <div class="dashboard-card">
              <%= cl_image_tag bar.photos.first.key, height: 120, width: 190, crop: :fill %>
              <div class="dashboard-card-details">
                <h5><%= bar.name %></h5>
                <div class="booking-address">
                  <%= bar.address %>
                </div>
                </diV>
                <div class="dashboard-card-booking-guests">
                  <p><%= bar.capacity %></p>
                  <p>place<%= "s" if bar.capacity > 1 %></p>
                </div>
                <%= link_to dashboard_owner_bookings_path(bar) do %>
                  <div class="dashboard-card-booking-show">Toutes les réservations</div>
                <% end %>
                <%= link_to bar_path(bar) do %>
                  <div class="dashboard-card-booking-show">Détails du bar</div>
                <% end %>
            </div>
            <ul>
              <% bar.bookings.order(starts_at: :asc).each do |booking| %>
                <% next if ["Terminé", "Annulé"].include? booking.state %>
                <li><%= render "components/dashboard_oneliner_cards", booking: booking %></li>
              <% end  %>
            </ul>
          <% end %>
        </div>
      </div>
    <% else %>
      <div class="empty-container">
        <h1>Vous n'avez pas encore de bar !</h1>
      </div>
    <% end %>
</div>

app/views/bars/show.html.erb
<%
    stimulus_data = ""
    if @bar.owner == current_user
      stimulus_data = <<-HTML
        data-controller="inline-edit"
        data-target="inline-edit.div"
        data-action="click->inline-edit#toggle click@window->inline-edit#close"
      HTML
      stimulus_data = stimulus_data.html_safe
    end
%>
<div class="bar-show">
  <div class="variable-width">
    <% @bar.photos.each do |photo| %>
      <%= cl_image_tag photo.key, height: 400, crop: :fit %>
    <% end %>
  </div>

  <div class="container bar-container">
    <div class="left-side d-flex flex-column">
      <div class="bar-details">
        <div class="bar-name">
          <h1 data-inline-edit-variable="name" <%= stimulus_data %>><%= @bar.name %></h1>
          <%= render "average_rating", bar: @bar %>
        </div> <!-- End bar-name -->
        <h5><%= icon("fas", "map-marker-alt") + nbspace + nbspace + @bar.address %></h5>
        <h5>
          <div>
            <%= icon("fas", "users") + nbspace %>
            <strong><%= @bar.capacity %></strong> participants maximum

          <div>
            <%= icon("fas", "tags") + nbspace %>
            <strong><%= @bar.price.to_s + nbspace %></strong>€ par participant
          </div>
        </h5>
      </div> <!-- End bar-details -->

      <div class="bar-description">
        <div class="tabs">
          <label for="tab-1">Description</label>
          <input id="tab-1" name="tabs-two" type="radio" checked="checked">
          <div>
            <p><%= @bar.description %></p>
            <div class="d-flex">
              <%= render "components/button_link", text: "back", link: bars_path %>
              <%=
                  if  @bar.owner == current_user
                    render "components/button_link", text: "Edit", link: edit_bar_path(@bar)
                  end
              %>
            </div>
          </div>
        </div>
        <div class="tabs">
          <label for="tab-2">Évaluations</label>
          <input id="tab-2" name="tabs-two" type="radio">
          <div>
            <div class="container reviews-container">
              <p><%= render "reviews" %></p>
            </div>
          </div>
        </div>
      </div> <!-- End bar-description -->
    </div> <!-- End left-side -->

    <div class="bar-booking-container">
      <div class="bar-booking">
        <div class="bar-price"
             data-controller="total-price"
             data-action="guest_number_change@window->total-price#update"
             data-total-price-bar-price = <%= @bar.price %>
           >
           <h4>Total price: <strong><span data-target="total-price.amount"><%= @bar.price * 2 %></span>€</strong></h4>
           <div class="bar-price-details">
             <p>Prix par participant : <span data-target="total-price.barPrice"><%= @bar.price %></span>€</p>
           </div> <!-- End bar-price-details -->
        </div> <!-- End bar-price -->

        <div class="booking-form">
          <%= render "booking_form" %>
        </div> <!-- End booking-form -->
        <%= render "components/button", text: "Réserver", type: "submit", form: "new_booking" %>
      </div> <!-- End bar-booking -->

      <div class="bar-empty"></div>
    </div> <!-- End bar-booking-container -->
  </div> <!-- End container -->
</div> <!-- End bar-show -->