config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users

  # UX redirections
  get '/dashboard', to: redirect("/dashboard/bookings")
  get '/dashboard/bars/:id', to: redirect("/dashboard/bars")

  get '/dashboard/bookings', to: 'bookings#index', as: "dashboard_bookings"
  get '/dashboard/bars', to: 'bars#owner_index', as: "dashboard_bars"
  get '/dashboard/bars/:bar_id/bookings', to: 'bookings#owner_index', as: "dashboard_owner_bookings"

  resources :bars, except: :destroy do
    resources :bookings, only: %i[create]
  end

  resources :bookings, except: %i[index create] do
    resources :reviews, only: %i[create]
  end

  post '/bookings/:id/cancellation', to: 'bookings#cancel', as: "booking_cancellation"
end

app/models/booking.rb
# frozen_string_literal: true

##
# Booking Model
# Has a bar to book by a user
# The booking takes place during some time, for a certain number of attendees at a certain price
class Booking < ApplicationRecord
  belongs_to :bar
  belongs_to :user
  has_one :review, dependent: :nullify

  validates :amount, :starts_at, :ends_at, :state, :guest_number, presence: true

  DATE_TRANSLATIONS = {
    'Monday': 'Lundi',
    'Tuesday': 'Mardi',
    'Wednesday': 'Mercredi',
    'Thursday': 'Jeudi',
    'Friday': 'Vendredi',
    'Saturday': 'Samedi',
    'Sunday': 'Dimanche',
    'January': 'Janvier',
    'February': 'Février',
    'March': 'Mars',
    'April': 'Avril',
    'May': 'Mai',
    'June': 'Juin',
    'July': 'Juillet',
    'August': 'Août',
    'September': 'Septembre',
    'October': 'Octobre',
    'November': 'Novembre',
    'December': 'Décembre'
  }

  def date_in_french
    string = starts_at.in_time_zone("CET").strftime("Le %A %d  %B, de %Hh%M à ")
    string += ends_at.in_time_zone("CET").strftime("%Hh%M")
    DATE_TRANSLATIONS.each { |en, fr| string.gsub!(Regexp.quote(en), fr) }

    return string
  end
end

app/controllers/bookings_controller.rb
# frozen_string_literal: true

class BookingsController < ApplicationController
  before_action :set_booking, only: %w[show edit update cancel]
  before_action :set_bar, only: %w[create owner_index]
  after_action :verify_authorized, only: :index, unless: :skip_pundit?
  skip_after_action :verify_policy_scoped, only: :index

  def show
    authorize @booking
    @bar = @booking.bar
    @review = Review.new
  end

  def edit
    authorize @booking
  end

  def update
    @booking.update(booking_params)
    authorize @booking
    @booking.save
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.bar = @bar
    @booking.amount = @bar.price * @booking.guest_number
    @booking.state = "À venir"
    authorize @booking

    @booking.save
    redirect_to booking_path(@booking)
  end

  def index
    @bookings = current_user.bookings.order(starts_at: :desc)
    update_booking_state
    authorize @bookings
  end

  def owner_index
    @bookings = @bar.bookings.order(starts_at: :desc)
    update_booking_state
    authorize @bookings
  end

  def cancel
    @booking.state = "Annulé"
    @booking.cancelled_by = current_user.id
    @booking.save
    authorize @booking
    redirect_to booking_path(@booking)
  end

  private

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def set_bar
    @bar = Bar.find(params[:bar_id])
  end

  def booking_params
    params.require(:booking).permit(
      :amount,
      :starts_at,
      :ends_at,
      :guest_number,
      :state
    )
  end

  def update_booking_state
    @bookings.each do |booking|
      next unless booking.state == "À venir"

      if Time.zone.now > booking.ends_at
        booking.state = "Terminé"
        booking.save
      end
    end
  end
end

app/views/bookings/_bookings_list.html.erb
<% @bookings.each do |booking| %>
  <div class="dashboard-card">
    <div class="dashboard-card-photo">
      <div class="status-tag status-tag-left <% if booking.state == "Annulé" %>
            <%= "tag-red" %>
          <% elsif booking.state == "Terminé" %>
            <%= "tag-blue" %>
          <% end %>"><%= booking.state %></div>
      <%= cl_image_tag booking.bar.photos.first.key, height: 120, width: 190, crop: :fill %>
    </div>
    <div class="dashboard-card-details">
      <strong><div class="booking-dates">
          <div class="booking-day">Le <%= booking.starts_at.strftime("%d/%m/%Y") %></div>
          <p>-</p>
          <div class="booking-hours"><%= booking.starts_at.hour %>h&nbsp&nbsp<i class="fas fa-arrow-right"></i>&nbsp&nbsp<%= booking.ends_at.hour %>h</div>
        </div></strong>
        <div class="blank-div"></div>
        <h5><%= booking.bar.name %></h5>
        <div class="booking-address">
          <%= booking.bar.address %>
        </div>
    </div>
    <div class="dashboard-card-booking-guests">
      <p><%= booking.guest_number %></p>
      <p>invité<%= "s" if booking.guest_number > 1 %></p>
    </div>
    <%= link_to booking_path(booking) do %>
      <div class="dashboard-card-booking-show">Détails</div>
    <% end %>
  </div>
<% end %>

app/views/bookings/_review_form.html.erb
<div class="add-review" data-controller="star-rating">
  <h3 class="review-form-header">C'est le moment d'ajouter un commentaire...</h3>
  <div class="stars" data-action="mouseleave->star-rating#showRating">

<%
    stimulus_hooks = {
      "data-target" => "star-rating.star",
      "data-action" => "click->star-rating#setRating \
                        mouseover->star-rating#chooseRating"
    }
%>

    <% 5.times do |i| %>
      <% stimulus_hooks["data-id"] = i + 1 %>
      <div class="star"><%= icon("far", "star", stimulus_hooks) %></div>
    <% end %>
  </div>

  <%= simple_form_for [@booking, @review] do |f| %>
    <%= f.input :content, label: false %>
    <%= f.input :rating, as: :hidden, input_html: { data: { target: "star-rating.form" } } %>
    <%= render "components/button", text: "Add a review", form: "new_review", type: "submit"%>
  <% end %>
</div>

app/views/bookings/edit.html.erb
<h1>Bookings#edit</h1>
<p>Find me in app/views/bookings/edit.html.erb</p>

app/views/bookings/index.html.erb
<div class="dashboard">
  <%= render "components/dashboard_menu" %>
  <% if @bookings.first.is_a? Booking %>
      <div class="dashboard-content">
        <div class="bookings-content">
          <h1>Mes réservations</h1>
          <%= render "bookings_list", bookings: @bookings %>
        </div>
      </div>
  <% else %>
    <%= render "components/dashboard_menu" %>
    <div class="empty-container">
      <h1>Vous n'avez pas encore de réservation !</h1>
    </div>
  <% end %>
</div>

app/views/bookings/owner_index.html.erb
<div class="dashboard">
  <%= render "components/dashboard_menu" %>
  <% if @bookings.first.is_a? Booking %>
    <div class="dashboard-content">
      <div class="bookings-content">
        <h1><%= @bookings.first.bar.name %></h1>
        <h2>Détail des réservations</h2>
        <%= render "bookings_list", bookings: @bookings %>
      </div>
    </div>
  <% else %>
    <div class="empty-container">
      <h1>Vous n'avez pas encore de réservation pour ce bar !</h1>
    </div>
  <% end %>
</div>

app/views/bookings/show.html.erb
<div class="dashboard">
  <%= render "components/dashboard_menu" %>
  <div class="dashboard-content">
    <div class="bookings-content">
      <h1>Détails de la réservation</h1>
      <div class="d-flex justify-content-around w-100">
        <div class="left-side mt-5">
          <% if @booking.state == "Terminé" && current_user == @booking.user %>
            <% if @booking.review %>
              <div class="your-review">
                <h2>Votre évaluation</h2>
                <br>
                <% @booking.review.rating.times do %>
                  <i class="fas fa-star"></i>
                <% end %>
                <% (5 - @booking.review.rating).times do %>
                  <i class="far fa-star"></i>
                <% end %>
                <br>
                <div class="your-review-content">
                  &nbsp&nbsp<i class="fas fa-quote-left"></i>&nbsp&nbsp&nbsp<em><%= @booking.review.content %></em>
                </div>
              </div>
            <% else %>
              <%= render "review_form" %>
            <% end %>
          <% end %>
          <% if @booking.state == "À venir" %>
            <form action="<%= booking_cancellation_path %>" method="post" id="cancellation_cta" onSubmit="return confirm('Êtes-vous sûr de vouloir annuler?');">
              <%= render 'components/button', text: "Annuler la réservation", type: "submit", form: "cancellation_cta", class:"cancellation-button" %>
              <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
            </form>
            <% if current_user == @booking.user %>
              <form action="mailto:<%= @bar.owner.email %>" id="owner-mailer">
                <%= render 'components/button', text: "Envoyer un email au propriétaire", type: "submit", form: "owner-mailer" %>
                <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
              </form>
            <% else %>
              <form action="mailto:<%= @booking.user %>" id="user-mailer">
                <%= render 'components/button', text: "Envoyer un email au locataire", type: "submit", form: "user-mailer" %>
                <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
              </form>
            <% end %>
          <% end %>
          <% if @booking.state == "Annulé" %>
            <h3 class="red">Cette réservation a été annulée <% if @booking.cancelled_by == current_user.id %><%= "par vous" %><% elsif @booking.user == current_user %><%= "par le propriétaire" %><% else %><%= "par le locataire" %><% end %>.</h3>
          <% end %>
        </div>
        <div class="bar-infos">
          <div class="status-tag status-tag-right <% if @booking.state == "Annulé" %>
            <%= "tag-red" %>
          <% elsif @booking.state == "Terminé" %>
            <%= "tag-blue" %>
          <% end %>"><%= @booking.state %></div>
          <%= link_to bar_path(@bar) do %>
            <div class="bar-photo" style="background-image: url(<%= cl_image_path @bar.photos.first.key %>); background-size: cover; background-position: center"></div>
          <% end %>
          <div class="bar-text">
            <h2><%= @bar.name %></h2>
            <div class="bar-address">
              <h5><%= @bar.address %></h5>
              <%= link_to "https://www.google.com/maps/dir//#{@bar.address.gsub(" ", "+")}", target: :_blank do %>
                <i class="fas fa-directions"></i>
              <% end %>
            </div>
            <br>
            <h5><%= @booking.date_in_french %></h5>
            <h5><%= pluralize @booking.guest_number, "participants" %></h5>
            <br>
            <h5>Prix total: <%= @booking.amount %>€</h5>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>